### PR TITLE
SQL plugin docs for basic usage

### PR DESCRIPTION
**Pull request by dai-chen**
*Issue #, if available:*

*Description of changes:* Adding 4 new documents for basic usage of SQL plugin which are generated from template and test code in issue https://github.com/opendistro-for-elasticsearch/sql/issues/293.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aetter** [comment]
Hey @dai-chen, this looks really good. Any chance you can use [fenced code blocks with highlighting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) rather than the indented version, or is that a high LOE given the tools you're using?

    ```json
    {
      "error": {
        "reason": "Invalid SQL query",
        "details": "Field [unknown] cannot be found or used here.",
        "type": "SemanticAnalysisException"
      },
      "status": 400
    }
    ```

**Comment by dai-chen** [comment]
> Hey @dai-chen, this looks really good. Any chance you can use [fenced code blocks with highlighting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) rather than the indented version, or is that a high LOE given the tools you're using?
> 
> ```
> ```json
> {
>   "error": {
>     "reason": "Invalid SQL query",
>     "details": "Field [unknown] cannot be found or used here.",
>     "type": "SemanticAnalysisException"
>   },
>   "status": 400
> }
> ```
> ```

Hi @aetter, thanks for the review! Sure, will change it. I'm still new to Pandoc. Do you happen to know if this is supported by Pandoc? The docs in this PR were just converted from ReST docs in my https://github.com/opendistro-for-elasticsearch/sql/pull/302. If no luck, I can do it manually. Thanks!

**Comment by aetter** [comment]
@dai-chen, so it looks to me like Pandoc prefers indented code blocks for whatever reason, but if you specify a language, it uses fenced blocks. So rather than:

```
SQL query::

   >> curl -H 'Content-Type: application/json' -X POST localhost:9200/_opendistro/_sql -d '{
     "query" : "SELECT * FROM accounts"
   }'
```

Try:

```
SQL query:

.. code:: sql (or bash or json)

   >> curl -H 'Content-Type: application/json' -X POST localhost:9200/_opendistro/_sql -d '{
     "query" : "SELECT * FROM accounts"
   }'
```

**Comment by dai-chen** [comment]
@aetter Thanks! Good to know this. Will do it manually this time and change my document generator for future use.

**Comment by dai-chen** [comment]
@aetter I've finished the changes. Because I don't know how it looks on GitHub Pages, I just check the how it's rendered on GitHub. If possible, please help double check if any more changes needed. Thanks!

**Comment by aetter** [comment]
Awesome, thanks a bunch @dai-chen. The only issue I'm seeing now is that the code is unnecessarily indented and harder to copy and paste, but I'll fix it manually post-merge and trust that you'll handle it on your side for the next content drop. 👍

**Comment by dai-chen** [comment]
> Awesome, thanks a bunch @dai-chen. The only issue I'm seeing now is that the code is unnecessarily indented and harder to copy and paste, but I'll fix it manually post-merge and trust that you'll handle it on your side for the next content drop. 👍

Thanks a lot! Will change my doc generator accordingly. :)

**Comment by aetter** [comment]
No worries! Cleanup should be live now: https://github.com/opendistro/for-elasticsearch-docs/commit/21c742d2e1856218c64aacebf9b6b3710129ca55

**Pull request merged**
