### PR TITLE
Add missing sql settings

### PR DESCRIPTION
**Pull request by liz-snyder-aws**
*Description of changes:*

Adding missing settings per https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/user/admin/settings.rst

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by liz-snyder-aws** [comment]
@aetter @chloe-zh for some reason it's not letting me add reviewers so tagging here for visibility

**Review by chloe-zh — COMMENTED** [review]
Thanks for the changes!
I remember we have removed these settings but then added them back and deprecated them. Could you take a look to see if these settings are necessary to add to the docs accordingly?  @dai-chen

**Comment by liz-snyder-aws** [comment]
Thanks @chloe-zh. We received feedback that the “opendistro.sql.engine.new.enabled” setting must be set to true in order for the [date and time](https://github.com/opendistro-for-elasticsearch/sql/pull/746) SQL functions to work in Elasticsearch 7.9. Looking into that led me to realize that the setting wasn't documented in the ODFE docs. Maybe @dai-chen can shed some light on this.

**Review by aetter — APPROVED** [review]

**Comment by dai-chen** [comment]
These 2 settings were added later without updating the documentation. @chloe-zh I guess you said is for OpenSearch setting docs.

**Review by chloe-zh — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
