### PR TITLE
Adds content on generating your own certificates

### PR DESCRIPTION
**Pull request by aetter**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RMKD** [comment]
This looks like excellent detail! I should be able to test on a vanilla build in the next couple of days. 

One comment that might be worth adding is whether there is any value to generating unique node-specific keys (which is a pattern I've seen in someone's documentation but seems like unnecessary complexity).

The other gotcha that may be worth noting is that that the hash for `kibanaserver` in `internal_users.yml` needs to correspond with any password supplied in `kibana.yml` and that the `-cd ../securityconfig/` clause is invoking the default `internal_users.yml` file (among the others in that directory).

**Comment by ulab** [comment]
> When prompted, provide a password.

I was not asked for a password without "-aes256" and was a little confused. Perhaps change this to "With this option you have to provide a password." to make it clearer?

> openssl req -new -x509 -sha256 -key private.key -out root-ca.pem

The generated keyfile is named "root-ca-key.pem", not "private.key".

Other questions that came to mind:

- Does each node need its own certificate?
- Does the CN of the certificate have to match the hostname (as it does for web certificates)?

**Comment by aetter** [comment]
Hi @RMKD and @ulab, thanks for reviewing. Point by point:

- Unique node-specific keys: I don't think it's necessary, no. I'll get confirmation pre-merge.
- Password hash: I've added a couple links that explain what's going on when you run this command.
- `aes256`: Sure, reworded slightly.
- `root-ca-key.pem`: Typo, thanks for catching. Fixed.
- Unique node certificates: Like the unique keys, I'm investigating here. My gut is "yes to individual certificates, no to individual keys."
- Yes, if you've enabled `opendistro_security.ssl.transport.enforce_hostname_verification`. I've added a note and link.

**Comment by aetter** [comment]
@hardik-k-shah has advised me to recommend one key per certificate so that you're not copying what is meant to be a private file across multiple machines---seems legit. :)

I'm going to go ahead and merge, but feel free to open new issues or PRs if you have thoughts. Thanks again for the reviews!

**Pull request merged**
